### ISSUE TITLE
Expand color-coding scheme. 

### ISSUE THREAD

**Issue by raplima** [marcosbr/predictive-geology-maps#19]
**Is your feature request related to a problem? Please describe.**
Feedback from the first workshop. #14 introduced code to generate a file that can be used to automatically create a colormap that converts the integer values of the`class.tif` output to the categories listed in `SIGLA_UNID`, including the standardized colors, that can be used in QGIS. The program could generate a similar file to be used with ArcGIS. 

**Describe the solution you'd like**
Create a colormap file that will allow ArcGIS users to quickly convert integer to lithology. 

**Describe alternatives you've considered**
Generate a vectorized `class.shp`  based on `class.tif`? Then users should be able to have the same configuration for both `Litologia.shp` and the output of the program.

**Comment by RichardScottOZ** [comment]
Yes, you can just map them via a dictionary and make in a column in your shapefile, too - then they can do what they like.

**Comment by raplima** [comment]
Thanks for the feedback @RichardScottOZ! We will try to implement it that way.

**Comment by raplima** [comment]
Adressed with #23 and #24 .
