### ISSUE TITLE
SIGLA_UNID output location

### ISSUE THREAD

**Issue by raplima** [marcosbr/predictive-geology-maps#32]
Currently the program creates the `SIGLA_UNID.csv` file in the same input folder from where the lithology file is located. I think this should be written in the ` self.dir_out` so everything the program generates is at the same location

**Comment by marcosbr** [comment]
Fix at [commit](https://github.com/marcosbr/predictive-geology-maps/commit/295e654905491cc18c0c7266bf1d4254b52ea9b3). #33

**Comment by raplima** [comment]
Great, thanks!
