### ISSUE TITLE
New options for GUI

### ISSUE THREAD

**Issue by marcosbr** [marcosbr/predictive-geology-maps#41]
The UI should have a checkbox (previously selected) that the user chooses to run the PCA on the multi-band raster (default value: True) variable name:
> self.run_pca

**Comment by raplima** [comment]
Should we have an option like "use enough components to explain \#% of the variance" (where the user selects the percentage from a dropdown)?

**Comment by marcosbr** [comment]
> Should we have an option like "use enough components to explain #% of the variance" (where the user selects the percentage from a dropdown)?

I like that idea!

**Comment by marcosbr** [comment]
- [ ] Run PCA (option to disable and a dropdown to select #% of the variance
- [ ] Option to run with coordinates as features in the model
